In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [26]:
df=pd.read_csv('C:\\Users\\mrudu\\OneDrive\\Desktop\\ml projects\\Lab 21 House_Rent_Dataset.csv')

In [27]:
df.head(2)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner

In [28]:
df.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

In [30]:
df.describe()

               BHK          Rent         Size     Bathroom
count  4746.000000  4.746000e+03  4746.000000  4746.000000
mean      2.083860  3.499345e+04   967.490729     1.965866
std       0.832256  7.810641e+04   634.202328     0.884532
min       1.000000  1.200000e+03    10.000000     1.000000
25%       2.000000  1.000000e+04   550.000000     1.000000
50%       2.000000  1.600000e+04   850.000000     2.000000
75%       3.000000  3.300000e+04  1200.000000     2.000000
max       6.000000  3.500000e+06  8000.000000    10.000000

In [31]:
df = df.drop(['Posted On', 'Floor', 'Area Locality'], axis=1)
df

,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2,10000,1100,Super Area,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2,20000,800,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2,17000,1000,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2,10000,800,Super Area,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2,7500,850,Carpet Area,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...
4741,2,15000,1000,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,3,29000,2000,Super Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,3,35000,1750,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,3,45000,1500,Carpet Area,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2,15000,1000,Carpet Area,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [32]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import sklearn.metrics as metrics
import category_encoders as ce
from sklearn.preprocessing import MinMaxScaler

In [33]:
categorical_cols = df.select_dtypes(include = 'object').columns
categorical_cols

Index(['Area Type', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Point of Contact'],
      dtype='object')

In [34]:
for col in categorical_cols:
    print(f"{col} : {df[col].nunique()}")

Area Type : 3
City : 6
Furnishing Status : 3
Tenant Preferred : 3
Point of Contact : 3

In [35]:
x=df.drop(columns='Rent')
y=df['Rent']

In [36]:
encoder = ce.LeaveOneOutEncoder(return_df=True)
x=encoder.fit_transform(x,y)

In [37]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [38]:
x_df = pd.DataFrame(x)
x_df

,0,1,2,3,4,5,6,7
0,0.2,0.136421,0.273162,0.004388,0.009553,0.017960,0.111111,0.003219
1,0.2,0.098874,0.273074,0.004130,0.487075,0.017809,0.000000,0.003165
2,0.2,0.123905,0.273100,0.004207,0.487114,0.017854,0.000000,0.003181
3,0.2,0.098874,0.273162,0.004388,0.009553,0.017960,0.000000,0.003219
4,0.2,0.105131,0.999941,0.004452,0.009593,0.587919,0.000000,0.003233
...,...,...,...,...,...,...,...,...
4741,0.2,0.123905,0.999871,0.124704,0.487140,0.017884,0.111111,0.003192
4742,0.4,0.249061,0.272994,0.124486,0.486957,0.017673,0.222222,0.003116
4743,0.4,0.217772,0.999683,0.124392,0.486879,0.017582,0.222222,0.999656
4744,0.4,0.186483,0.999589,0.124236,0.486748,0.995587,0.111111,0.999541
4745,0.2,0.123905,0.999871,0.124704,0.009472,0.587449,0.111111,0.003192

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=40)

In [40]:
x_train.shape, x_test.shape

((3796, 8), (950, 8))

In [41]:
model_rfr = RandomForestRegressor(n_estimators=7)
model_dt = DecisionTreeRegressor()
model_lr = LinearRegression()

models = [model_rfr, model_dt, model_lr]

In [42]:
for model in models :
    print(f"fitting model: {model}")
    model.fit(x_train,y_train)

fitting model: RandomForestRegressor(n_estimators=7)
fitting model: DecisionTreeRegressor()
fitting model: LinearRegression()

In [43]:
for model in models:
    print(f"score of {model}: ")
    print(f"  for training data: {model.score(x_train, y_train)}")
    print(f"  for test data: {model.score(x_test, y_test)}")

score of RandomForestRegressor(n_estimators=7):
  for training data: 0.7901171992254359
  for test data: 0.7486476493846506
score of DecisionTreeRegressor():
  for training data: 1.0
  for test data: 0.9161964582378971
score of LinearRegression():
  for training data: 0.29297105483208685
  for test data: 0.4349171880607351

In [44]:
def regression_results(y_true, y_pred):
    explained_variance = metrics.explained_variance_score(y_true, y_pred)
    mean_absolute_error = metrics.mean_absolute_error(y_true, y_pred)
    mse = metrics.mean_squared_error(y_true, y_pred)
    median_absolute_error = metrics.median_absolute_error(y_true, y_pred)
    r2 = metrics.r2_score(y_true, y_pred)
    print('explained_variance: ', round(explained_variance,4))    
    print('r2: ', round(r2,4))
    print('MAE: ', round(mean_absolute_error,4))
    print('MSE: ', round(mse,4))
    print('RMSE: ', round(np.sqrt(mse),4))
    print('Median absolute error: ',round(median_absolute_error,4))

In [45]:
for model in models[:]:
    y_predicted = model.predict(x_test)

    print(f"Report: {model}")
    print(f"{regression_results(y_test, y_predicted)}\n")

Report: RandomForestRegressor(n_estimators=7)
explained_variance:  0.7489
r2:  0.7486
MAE:  2275.815
MSE:  830265636.3616
RMSE:  28814.3304
Median absolute error:  0.0
None

Report: DecisionTreeRegressor()
explained_variance:  0.9162
r2:  0.9162
MAE:  1225.02
MSE:  276819376.3063
RMSE:  16637.8898
Median absolute error:  0.0
None

Report: LinearRegression()
explained_variance:  0.4363
r2:  0.4349
MAE:  22345.7924
MSE:  1866578288.6182
RMSE:  43203.9152
Median absolute error:  16809.2852
None

In [46]:
import joblib

In [47]:
models = [model_rfr, model_dt, model_lr]